### PR TITLE
Add typescript type definition

### PR DESCRIPTION
**Pull request by scalder27**
@stylesuxx hi again!

I wrote some typescript type definitions for a library. Maybe it could be useful.
Ideally, it should be placed in the repository along with the code. If you have no objections, of course.

### CODE REVIEW

**Comment by stylesuxx** [comment]
Hey @scalder27,
if it is useful for you, it might be useful for someone else, so I see no harm in adding it.

Are you using this library in prod? Are you interested in co-maintaining?

I have very limited time, so any help I can get is very much appreciated.

**Comment by scalder27** [comment]
@stylesuxx awesome!

Everyone using typescript forced to write their own types or to add it to DefinitelyTyped package, or create PR to the library. Most organic and easy to keep it up to date variant - types in the library. This types could be useful not only for typescript devs, IDEs could use it for a clever intellisense for regular js.

I'm not using this library in prod. Not yet. A project I'm working on in an active development phase. But, eventually, I'm going to. So, I'm happy to help, though I'm not sure how much time I'll be able to spend.

**Comment by scalder27** [comment]
@stylesuxx hello! It's me. Again =)

**Comment by scalder27** [comment]
@stylesuxx any news?

**Comment by scalder27** [comment]
@stylesuxx knock-knock

**Comment by scalder27** [comment]
@stylesuxx hi!

**Comment by stylesuxx** [comment]
Again, thank you for your contribution, merged and published under version 1.1.0.

**Comment by scalder27** [comment]
@stylesuxx cool! Thank you very much!

**Pull request merged**
