### PR TITLE
Add support for GraphQL 15

### LINKED ISSUE #28: Compatibility with graphql 15.x
Can this package be updated to support graphql 15.x?

### PR DESCRIPTION
**Pull request by j0k3r**
- Upgrade to latest dev deps (babel, eslint, tape)
- Add Node 12 & 14 to Travis
- Remove hard dependencies to GraphQL, must be on peerDependencies instead

Fix #28

### CODE REVIEW

**Comment by j0k3r** [comment]
Drop support for Node < 6.9

https://travis-ci.org/github/stylesuxx/graphql-custom-types/builds/704614471

image

**Comment by stylesuxx** [comment]
@j0k3r thank you for your contribution - just one question: where do you see the benefit in piping the test output through tap-dot? I always like to keep the dependencies as minimal as possible, although this being a dev dependency, it's not a big issue. Was just wondering if this is personal preference or if there is some benefit that I am missing.

I have no problem in keeping that dependency - was just wondering.

**Comment by j0k3r** [comment]
Oh yes sorry it was a personal preference of seeing dot instead of a long list of tests. I'll remove it

**Comment by stylesuxx** [comment]
Oh, and one more thing: you changed the `before-script` to `install`, interestingly enough when travis runs your PR - this is working. I initially had it in the install too, but it would not install the rest of the dependencies, as you can see from the failed build here => https://travis-ci.org/github/stylesuxx/graphql-custom-types/builds/704642264 any idea on why this could be happening? It seems to only install the provided dependency but not running an actual `npm install`.

**Comment by j0k3r** [comment]
Good catch, it worked for my PR because I've updated that `before_script` it after creating the PR. Which means node_modules were already cached in Travis cache.
I'll update the travis build to use `before_script` again :+1:

**Comment by stylesuxx** [comment]
It's OK - I simply added another step in the install section. Thanks again.

**Pull request closed without merging**
