### PR TITLE
Yet another updating graphql peer dependency

### PR DESCRIPTION
**Pull request by scalder27**
This package didn't work with graphql v0.10.1.

### CODE REVIEW

**Comment by scalder27** [comment]
@stylesuxx, please check the request. I had to fix tests because of changed API in graphql (https://github.com/graphql/graphql-js/releases/tag/v0.10.0)

**Comment by stylesuxx** [comment]
Thank you for you contribution.
If there are API changes, I think it would be best to publish a new major version.

Could you adjust https://github.com/stylesuxx/graphql-custom-types/pull/15/commits/dcc9746410e0536573d922f2f3f648e2b39fd23d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L26

to 0.10.0, then I will merge and publish a new version.

Thank you again.

**Comment by scalder27** [comment]
Glad to help!

I'm not sure that there is a need in publishing a new major version. There were zero changes in the actual API.

**Comment by scalder27** [comment]
I adjusted graphql version to 0.10.0.

**Comment by scalder27** [comment]
@stylesuxx is all ok now?

**Comment by scalder27** [comment]
@stylesuxx hi! Any news about PR?

**Comment by scalder27** [comment]
@stylesuxx hello!

**Comment by scalder27** [comment]
@stylesuxx any news?

**Comment by stylesuxx** [comment]
Thank you for your contribution and your patience.

Published new version to npm now.

**Comment by scalder27** [comment]
@stylesuxx cool! Thank you very much!

**Pull request merged**
