### PR TITLE
Parse and validate Values from Query Variables

### PR DESCRIPTION
**Pull request by Glavin001**
See https://github.com/graphql/graphql-js/issues/187 for example.

### CODE REVIEW

**Comment by Glavin001** [comment]
Until this is merged, my current workaround is to patch the exported `GraphQLCustomScalarType` class.
You can add the following before you start building your schema:

```javascript
// Fix custom-types
// See https://github.com/stylesuxx/graphql-custom-types/pull/4
import { GraphQLScalarType } from 'graphql';
import { Kind } from 'graphql/language';
class GraphQLCustomScalarType extends GraphQLScalarType {
  constructor(name, description, parser) {
    super({
      name: name,
      description: description,
      serialize: value => {
        return value;
      },
      parseValue: value => {
        const ast = {
          kind: Kind.STRING,
          value: value
        };
        return parser(ast);
      },
      parseLiteral: ast => {
        return parser(ast);
      }
    });
  }
}
require('graphql-custom-types').GraphQLCustomScalarType = GraphQLCustomScalarType;
```

**Comment by Glavin001** [comment]
@stylesuxx : Please merge and publish ASAP! Let me know if there is anything else I can do!

If you are no longer maintaining this package, also let me know, and I will fork and publish on my own to npm with your permission. Thanks!

**Comment by stylesuxx** [comment]
I merged this into dev a couple of days ago, wanted to wait if I get a PR for #5 to include it in the new release.

Thank you for your contribution and thank you for reminding me.

Published new version to NPM.

**Comment by Glavin001** [comment]
> wanted to wait if I get a PR for #5 to include it in the new release.

Not something I needed, however here's a quick Pull Request I whipped up. Let's see if the tests do pass now.
https://github.com/stylesuxx/graphql-custom-types/pull/6

> Published new version to NPM.

Thank you! This is great.

**Pull request merged**
